### ISSUE TITLE
Implémentation tiles random

### ISSUE THREAD

**Issue by Kokonaught** [MySweetWhomp/diversityjam#3]
UI BJR CER LES PETITES HERBES

**Comment by paulloz** [comment]
@Kokonaught Tu veux quoi comme ratio tile normal / tile spécial ? Et comme ratio entre les tiles spéciaux ?

**Comment by Kokonaught** [comment]
Ratio égal entre les tiles spéciaux,
Un tile spécial pour 3 tiles normaux, ou pour 2, faudrait tester.
