### ISSUE TITLE
Laisser le personnage sur la zone de jeu quand le joueur se déconnecte

### ISSUE THREAD

**Issue by Kokonaught** [MySweetWhomp/diversityjam#5]
- Quand un joueur se déconnecte, au lieu de supprimer le personnage, on le laisse sur la zone de jeu en mode "tombe" (qui sera remplacée par un asset du personnage en position foetale ou autre)
- Le personnage conserve son comportement vis à vis des autres personnages
- A définir : son influence sur la jauge de morale : compte-t'il toujours comme un personnage à 0 de moral ou bien est-il exclu du calcul (risque de faire tendre la jauge vers le bas très rapidement s'il compte dans le calcul, et potentiellement de très vite tuer la room) : peut-être prévoir un sprite différent pour un personnage "mort" (en PLS) et un personnage déconnecté (qui dort ?) ?

**Comment by paulloz** [comment]
Amha un perso sur le plateau compte, point barre. L'inverse casse le principe du jeu...
Sinon on le considère comme quoi ? Une case vide ? Dans ce cas, ça casse complètement les personnages dont la règle est d'avoir le moins de cases vides possibles à ses côtés par exemple.

**Comment by Kokonaught** [comment]
Le joueur endormi fonctionnerait de la façon suivante : 
- il compte comme une case pleine du type du personnage en question
- son moral au moment de la déconnexion reste décompté dans le moral global mais devient fixe

**Comment by Kokonaught** [comment]
Concept updaté : 
- quand un personnage tombe à 0 de moral il reste sur le terrain avec son moral à 0 : le jeu propose alors dans le message de gameover de créer un nouveau personnage au joueur
- quand un personnage arrive à mener son moral au max, il reste sur le terrain avec son moral au max et le jeu propose au jouer de créer un nouveau personnage dans la room
- quand un joueur se déconnecte, son personnage reste dans la room endormi avec son niveau de moral figé au niveau auquel il était
- Ajouter un bouton qui permet de respawn immédiatement un nouveau perso : le perso précédent s'endort alors.

**Comment by paulloz** [comment]
À quel moment on décide de supprimer une room du coup ?

**Comment by Kokonaught** [comment]
Quand la société s'effondre non ?

**Comment by paulloz** [comment]
Oui forcément, mais pour l'instant par exemple les salles sont aussi supprimées quand elles sont vides. Ça évite d'avoir des salles inutiles affichées sur le title...

**Comment by Kokonaught** [comment]
On peut soit supprimer la salle vide, soit laisser un court délai (ptêt une heure) vu que la salle vide reste une salle qui s'est "construite", potentiellement depuis un petit moment et que c'est peut-être un peu cash de la supprimer direct (surtout si y'a genre un soucis sur le serveur par exemple)

**Comment by paulloz** [comment]
Je fais un ticket à part pour le _freeze_ une fois à 100% de bonheur.
