### ISSUE TITLE
Fixer l'indicateur de temps pour une room active

### ISSUE THREAD

**Issue by Kokonaught** [MySweetWhomp/diversityjam#8]
L'afficher en heures, minutes, secondes

**Comment by paulloz** [comment]
C'est acutellement en _X min and Y sec_. Est-ce que les heures sont utiles ?

**Comment by Kokonaught** [comment]
C'est actuellement tout buggé chez moi dans ce cas ^^ 
C'est genre en hexa
![sans titre](https://cloud.githubusercontent.com/assets/13772460/14636817/f33b8706-062d-11e6-939e-b4c07171169f.png)

**Comment by paulloz** [comment]
Pic please.  
Also, il faut trouver une typo moins dégueulasse amha.

**Comment by Kokonaught** [comment]
J'aime bien cette typo x) mais je peux en trouver une autre. j'ai updaté mon commentaire avec un screen.

**Comment by paulloz** [comment]
C'est pas en hexa, c'est le _sec_ de _Y sec_ (il devrait y avoir un espace, mais je n'ai pas pushé les dernières modifs).
Dans tous les cas, la valeur négative n'est pas normale.

**Comment by Kokonaught** [comment]
Alors ça me le fait pas sur mon win 7, je vérifie si je te dis pas de la merde et je reviens

**Comment by Kokonaught** [comment]
Alors je confirme : Chrome win 8 : valeur cheloue que je t'ai envoyé
Firefox win 8 j'ai juste "up since" et pas de valeur derrière

Chrome win 7 ça roule
Firefow win 7 même soucis que firefox win8

**Comment by paulloz** [comment]
Un message d'erreur dans la console sous FF ?

**Comment by Kokonaught** [comment]
ça marche une fois FF updaté
